### ISSUE TITLE
Use of your parser in my oss project

### ISSUE THREAD

**Issue by mariotoffia** [zpatrick/go-parser#8]
Hi zpatrick,

I've taken your parser and extended (I'd guess you'd say destroyed) it to fit into my oss project to parse go source for documentation render in asciidoc. I hope it is ok for you to do so. I've acknowledged your work and link to your project from my README.md.

My project is [here](https://github.com/mariotoffia/goasciidoc). 

We have different licenses, but I hope that works well anyway?

Cheers,
 Mario

**Comment by zpatrick** [comment]
Hi Mario,

Of course it's fine, thanks for the shout out! Glad this turned out to be a useful starting point for you.

Good luck with your project,
Zack
